puts "🌱 Seeding spices..."

# Seed your database here

breakfast = Category.create(name: 'breakfast')
lunch = Category.create(name: 'lunch')
dinner = Category.create(name: 'dinner')
snack = Category.create(name: 'snack')
dessert = Category.create(name: 'dessert')
Meal.create(
  name: 'Egg Sandwich with Fruit',
  description: 'I love eggs and fruit in the morning!',
  category_id: dessert.id
)

Ingredient.create(name: "ground beef 85% lean", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "lean meat", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "very lean meat", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "medium-fat meat", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "chicken breast", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "ground turkey 85% lean", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "ground bison", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "chicken sausage", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "deer", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "flank steak", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "ham", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "lamb", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "new york strip", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "roast beef", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "salmon", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "sirloin", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "turkey bacon", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "turkey sausage", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "veal", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "egg", macro: 'protein', portion_unit: 'each', portion_quantity: 1)
Ingredient.create(name: "cottage cheese", macro: 'protein', portion_unit: 'oz', portion_quantity: 0.25)
Ingredient.create(name: "egg beaters", macro: 'protein', portion_unit: 'cup', portion_quantity: 0.25)
Ingredient.create(name: "catfish", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "clams", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "cod", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "canadian bacon", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "crawfish", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "grouper", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "haddock", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "lobster", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "mahi-mahi", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "mussels", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "perch", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "red snapper", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "scallops", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "sea bass", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "shrimp", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "tilapia", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "trout", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "tuna", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)
Ingredient.create(name: "protein powder", macro: 'protein', portion_unit: 'oz', portion_quantity: 1)

Ingredient.create(name: "starch", macro: 'starch', portion_unit: 'each', portion_quantity: 1)
Ingredient.create(name: "fruit", macro: 'fruit', portion_unit: 'each', portion_quantity: 1)
Ingredient.create(name: "rice", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.33)
Ingredient.create(name: "bagel", macro: 'starch', portion_unit: 'each', portion_quantity: 0.25)
Ingredient.create(name: "bread (slice)", macro: 'starch', portion_unit: 'each', portion_quantity: 1)
Ingredient.create(name: "bulgur wheat (cooked)", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "corn chips", macro: 'starch', portion_unit: 'each', portion_quantity: 10)
Ingredient.create(name: "corn tortilla 4 inch", macro: 'starch', portion_unit: 'each', portion_quantity: 1)
Ingredient.create(name: "hamburger bun", macro: 'starch', portion_unit: 'each', portion_quantity: 0.5)
Ingredient.create(name: "oatmeal (cooked)", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "oatmeal (dry)", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.25)
Ingredient.create(name: "pasta (dry)", macro: 'starch', portion_unit: 'oz', portion_quantity: 2)
Ingredient.create(name: "popcorn", macro: 'starch', portion_unit: 'cup', portion_quantity: 3)
Ingredient.create(name: "quinoa (cooked)", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.33)
Ingredient.create(name: "wheat tortilla 6 inch", macro: 'starch', portion_unit: 'each', portion_quantity: 1)
Ingredient.create(name: "whole grain cereal", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "beans (cooked)", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "pinto beans (cooked)", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "black beans (cooked)", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "kidney beans (cooked)", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "navy beans (cooked)", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "white beans (cooked)", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "garbanzo beans (cooked)", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "apple (medium)", macro: 'fruit', portion_unit: 'each', portion_quantity: 1)
Ingredient.create(name: "apple sauce", macro: 'fruit', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "apricot", macro: 'fruit', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "mango", macro: 'fruit', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "watermelon", macro: 'fruit', portion_unit: 'cup', portion_quantity: 1)
Ingredient.create(name: "cantelope", macro: 'fruit', portion_unit: 'cup', portion_quantity: 1)
Ingredient.create(name: "honey dew", macro: 'fruit', portion_unit: 'cup', portion_quantity: 1)
Ingredient.create(name: "rasberries", macro: 'fruit', portion_unit: 'cup', portion_quantity: 0.666)
Ingredient.create(name: "strawberries", macro: 'fruit', portion_unit: 'cup', portion_quantity: 1)
Ingredient.create(name: "blueberries", macro: 'fruit', portion_unit: 'cup', portion_quantity: 0.666)
Ingredient.create(name: "banana 4 inch", macro: 'fruit', portion_unit: 'each', portion_quantity: 1)
Ingredient.create(name: "kiwi", macro: 'fruit', portion_unit: 'each', portion_quantity: 1)
Ingredient.create(name: "nectarine", macro: 'fruit', portion_unit: 'each', portion_quantity: 1)
Ingredient.create(name: "orange", macro: 'fruit', portion_unit: 'each', portion_quantity: 1)
Ingredient.create(name: "peach", macro: 'fruit', portion_unit: 'each', portion_quantity: 1)
Ingredient.create(name: "pear", macro: 'fruit', portion_unit: 'each', portion_quantity: 1)
Ingredient.create(name: "plum", macro: 'fruit', portion_unit: 'each', portion_quantity: 1)
Ingredient.create(name: "fig", macro: 'fruit', portion_unit: 'each', portion_quantity: 2)
Ingredient.create(name: "pinneaple", macro: 'fruit', portion_unit: 'cup', portion_quantity: 0.75)
Ingredient.create(name: "papaya", macro: 'fruit', portion_unit: 'cup', portion_quantity: 1)
Ingredient.create(name: "cherries", macro: 'fruit', portion_unit: 'each', portion_quantity: 12)
Ingredient.create(name: "grapes", macro: 'fruit', portion_unit: 'each', portion_quantity: 15)
Ingredient.create(name: "grapefruit", macro: 'fruit', portion_unit: 'each', portion_quantity: 0.5)
Ingredient.create(name: "clementine", macro: 'fruit', portion_unit: 'each', portion_quantity: 2)
Ingredient.create(name: "acorn squash", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.75)
Ingredient.create(name: "corn", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "red potatoes", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "potatoes", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "russet potatoes", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "yukon gold potatoes", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "fingerling potatoes", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "sweet potatoes", macro: 'starch', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "honey", macro: 'starch', portion_unit: 'tbs', portion_quantity: 1)
Ingredient.create(name: "maple syrup", macro: 'starch', portion_unit: 'tbs', portion_quantity: 1)
Ingredient.create(name: "sugar", macro: 'starch', portion_unit: 'tbs', portion_quantity: 1)
Ingredient.create(name: "ketchup", macro: 'starch', portion_unit: 'tbs', portion_quantity: 3)

Ingredient.create(name: "mixed vegetables", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "broccoli", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "arugula", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "bean sprouts", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "iceberg lettuce", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "field greens", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "kale", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "leeks", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "spinach", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "romaine lettuce", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "beets", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "cauliflower", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "green bean", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "cucumber", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "eggplant", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "white mushrooms", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "brown mushrooms", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "portabello mushrooms", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "shitake mushrooms", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "yellow squash", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "zucchini", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "carrots", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "brussel sprouts", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "red pepper", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "green pepper", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "yellow pepper", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "orange pepper", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "tomato", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "green onion", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "yellow onion", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "red onion", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)
Ingredient.create(name: "white onion", macro: 'vegetable', portion_unit: 'cup', portion_quantity: 0.5)

Ingredient.create(name: "monterrey jack cheese", macro: 'fat', portion_unit: 'tbs', portion_quantity: 3)
Ingredient.create(name: "colby jack cheese", macro: 'fat', portion_unit: 'tbs', portion_quantity: 3)
Ingredient.create(name: "cheddar cheese", macro: 'fat', portion_unit: 'tbs', portion_quantity: 3)
Ingredient.create(name: "mozzarella cheese", macro: 'fat', portion_unit: 'tbs', portion_quantity: 3)
Ingredient.create(name: "sour cream", macro: 'fat', portion_unit: 'tbs', portion_quantity: 3)
Ingredient.create(name: "avocado", macro: 'fat', portion_unit: 'cup', portion_quantity: 0.25)
Ingredient.create(name: "butter", macro: 'fat', portion_unit: 'tsp', portion_quantity: 1)
Ingredient.create(name: "cream cheese", macro: 'fat', portion_unit: 'tbs', portion_quantity: 1)
Ingredient.create(name: "feta", macro: 'fat', portion_unit: 'cup', portion_quantity: 0.25)
Ingredient.create(name: "mayonaise", macro: 'fat', portion_unit: 'tsp', portion_quantity: 2)
Ingredient.create(name: "peanut butter", macro: 'fat', portion_unit: 'tsp', portion_quantity: 2)
Ingredient.create(name: "almond butter", macro: 'fat', portion_unit: 'tsp', portion_quantity: 2)
Ingredient.create(name: "avocado oil", macro: 'fat', portion_unit: 'tsp', portion_quantity: 1)
Ingredient.create(name: "canola oil", macro: 'fat', portion_unit: 'tsp', portion_quantity: 1)
Ingredient.create(name: "olive oil", macro: 'fat', portion_unit: 'tsp', portion_quantity: 1)
Ingredient.create(name: "coconut oil", macro: 'fat', portion_unit: 'tsp', portion_quantity: 1)
Ingredient.create(name: "vegetable oil", macro: 'fat', portion_unit: 'tsp', portion_quantity: 1)
Ingredient.create(name: "peanut oil", macro: 'fat', portion_unit: 'tsp', portion_quantity: 1)
Ingredient.create(name: "sesame oil", macro: 'fat', portion_unit: 'tsp', portion_quantity: 1)
Ingredient.create(name: "olives", macro: 'fat', portion_unit: 'each', portion_quantity: 10)
Ingredient.create(name: "taziki", macro: 'fat', portion_unit: 'tbs', portion_quantity: 6)
Ingredient.create(name: "unsweetened almond milk", macro: 'fat', portion_unit: 'cup', portion_quantity: 1)
Ingredient.create(name: "unsweetened coconut milk", macro: 'fat', portion_unit: 'cup', portion_quantity: 1)
Ingredient.create(name: "unsweetened cashew milk", macro: 'fat', portion_unit: 'cup', portion_quantity: 1)
Ingredient.create(name: "yogurt-based dressing", macro: 'fat', portion_unit: 'tbs', portion_quantity: 3)
Ingredient.create(name: "oil-based dressing", macro: 'fat', portion_unit: 'tsp', portion_quantity: 1)

breakfast.meals.create(
  name: 'Egg Sandwich with Fruit',
  description: 'I love eggs and fruit in the morning!'
)

MealIngredient.create(meal_id: 1, ingredient_id: 17, quantity: 2)
MealIngredient.create(meal_id: 1, ingredient_id: 68, quantity: 1)
MealIngredient.create(meal_id: 1, ingredient_id: 127, quantity: 1)
MealIngredient.create(meal_id: 1, ingredient_id: 42, quantity: 2)
MealIngredient.create(meal_id: 1, ingredient_id: 139, quantity: 1)

lunch.meals.create(
  name: 'Asian Meatballs',
  description: 'Delicious asian meatballs served with broccoli and rice.'
)

MealIngredient.create(meal_id: 2, ingredient_id: 3, quantity: 6)
MealIngredient.create(meal_id: 2, ingredient_id: 40, quantity: 3)
MealIngredient.create(meal_id: 2, ingredient_id: 107, quantity: 1)

snack.meals.create(
  name: 'Apples and Peanut Butter',
  description: 'My favorite snack'
)

MealIngredient.create(meal_id: 3, ingredient_id: 60, quantity: 1)
MealIngredient.create(meal_id: 3, ingredient_id: 137, quantity: 3)

puts "✅ Done seeding!"
